### ISSUE TITLE
Request for .XAC portion source code

### ISSUE THREAD

**Issue by Axel6430** [Cgettys/X4Converter#3]
Hi! I'm contacting you here because I'm not sure if you're still active on discord 😄 
I'd be very interested in having access to the source code for the .xac<->.dae portion of the converter. Do you still have it? I assume that's what the content of the "dead xac" folder in the refactor_memory branch is?

You can merge it with the current build but I'd be fine with doing it myself if you don't have the time.
Also, do you still have _arc's documentation on the .xac format (along with .xpm and .xsm) from [this thread](https://forum.egosoft.com/viewtopic.php?p=4308264#p4308264)'s OP?
Thanks!

**Comment by Cgettys** [comment]
https://github.com/Cgettys/X4Converter/commit/b8cc268df31f39da8ff259c924a081052715eb5f
I have always been here...
